In [4]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print('This is a numpy array:\n{}'.format(x))

This is a numpy array:
[[1 2 3]
 [4 5 6]]


In [12]:
from scipy import sparse

#Create a 2d NumPy array with a diagonal of one, with zeros everywhere else.
eye = np.eye(5)
print("NumPy array:\n",eye)

NumPy array:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
# Convert the NumPy array to a SciPy sparse matrix in CSR format
# Only the nonzero entries are stored

sparse_matrix = sparse.csr_matrix(eye)
print("SciPy sparse CSR matrix:\n",sparse_matrix)

SciPy sparse CSR matrix:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
